/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Documentation
         * @description Documentation page for the CryptoSharia API using Scalar.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API Documentation Page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI Spec
         * @description Retrieve the OpenAPI 3.1.0 specification for this API.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI Specification in JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Up
         * @description Register a new **regular user** (`role: member`) account. Users must verify their email before they can sign in.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Whether to trigger a verification email */
                    notify?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthSignupPostBody"];
                };
            };
            responses: {
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["AuthSignupPostResponse"];
                        };
                    };
                };
                /** @description Invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to register user */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Email
         * @description Verify a user email address using a secret token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthVerifyPostBody"];
                };
            };
            responses: {
                /** @description Email verified successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Invalid or missing token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Invalid or expired token */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to verify email */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign In
         * @description Authenticate with email and password. Returns access and refresh tokens.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthSigninPostBody"];
                };
            };
            responses: {
                /** @description Success, tokens and user metadata returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["AuthSigninPostResponse"];
                        };
                    };
                };
                /** @description Invalid email or password */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to process signin */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Out
         * @description Revoke a refresh token to end a session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthSignoutPostBody"];
                };
            };
            responses: {
                /** @description Refresh token revoked successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Missing or invalid refresh token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to revoke token */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Rotate refresh token and issue a new access token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthRefreshPostBody"];
                };
            };
            responses: {
                /** @description Success, new tokens and user metadata returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["AuthRefreshPostResponse"];
                        };
                    };
                };
                /** @description Missing or invalid refresh token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Refresh token is expired or revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to refresh token */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Retrieve profile information for the currently authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["AuthMeGetResponse"];
                        };
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to fetch user profile */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Retrieve a paginated list of all users. Requires permission: `users.read`.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    /** @description Search by name or email */
                    search?: string;
                    /** @description Filter by role name */
                    role?: "super_admin" | "admin" | "posts_manager" | "tokens_manager" | "member";
                    /** @description Filter by account status */
                    status?: "active" | "inactive" | "suspended" | "banned";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of users retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["UsersGetResponse"];
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Insufficient permissions to list users */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve users due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Detail
         * @description Retrieve detailed information for a specific user. Requires permission: `users.read` or ownership.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User details retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["UsersIdGetResponse"];
                        };
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Insufficient permissions to view this user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve user details due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Update an existing user profile. Requires permission: `users.update` or ownership.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UsersIdPatchBody"];
                };
            };
            responses: {
                /** @description User updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["UsersIdGetResponse"];
                        };
                    };
                };
                /** @description Invalid update data provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Insufficient permissions to update this user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to update user due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update User Status
         * @description Update the administrative status of a user (lifecycle management). Requires permission: `users.manage_status`
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UsersIdStatusPutBody"];
                };
            };
            responses: {
                /** @description User status updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["UsersIdGetResponse"];
                        };
                    };
                };
                /** @description Invalid status provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Insufficient permissions to manage user status */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to update status */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Assign Role
         * @description Assign or remove a role for a user. Requires permission: `users.manage_role`.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UsersIdRolePutBody"];
                };
            };
            responses: {
                /** @description Role assigned successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["UsersIdGetResponse"];
                        };
                    };
                };
                /** @description Invalid role provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Insufficient permissions to manage user roles */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to assign role due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Posts
         * @description Retrieve a list of posts with filtering, searching, and pagination support.
         */
        get: {
            parameters: {
                query?: {
                    /** @description List of content statuses to filter by.<br>Example: published,draft */
                    statuses?: ("draft" | "published" | "archived")[];
                    /** @description List of post sections to filter by.<br>Example: news,education,activity */
                    sections?: ("news" | "education" | "research" | "activity")[];
                    /** @description List of post types to filter by.<br>Example: article,video,webinar */
                    types?: ("article" | "webinar" | "video" | "headline")[];
                    /** @description List of post slugs to filter by.<br>Example: this-is-a-post,this-is-another-post */
                    slugs?: string[];
                    /** @description List of post slugs to exclude.<br>Example: this-is-a-post,this-is-another-post */
                    exclude?: string[];
                    search?: string;
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of posts retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PaginatedPostsGetItem"];
                        };
                    };
                };
                /** @description Invalid query parameters provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve posts due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Post by ID
         * @description Retrieve any post using its UUID regardless of its status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The UUID of the post */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Post retrieved successfully by ID */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PostsGetData"];
                        };
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve post due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Published Post by Slug
         * @description Retrieve a single published post using its slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The slug of the post */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published post retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PostsGetData"];
                        };
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Post not found or is not published */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve post due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tokens
         * @description Retrieve a list of cryptocurrency tokens with filtering, searching, and pagination support.
         */
        get: {
            parameters: {
                query?: {
                    /** @description List of content statuses to filter by.<br>Example: published,draft */
                    statuses?: ("draft" | "published" | "archived")[];
                    /** @description List of sharia statuses to filter by.<br>Example: halal,haram */
                    shariaStatuses?: ("halal" | "haram" | "syubhat")[];
                    /** @description List of token slugs to filter by.<br>Example: bitcoin,ethereum,sui */
                    slugs?: string[];
                    /** @description List of token slugs to exclude.<br>Example: bitcoin,ethereum,sui */
                    exclude?: string[];
                    search?: string;
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of tokens retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PaginatedTokensGetItem"];
                        };
                    };
                };
                /** @description Invalid query parameters provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve tokens due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token by ID
         * @description Retrieve any cryptocurrency token using its UUID regardless of its status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The UUID of the cryptocurrency token */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token retrieved successfully by ID */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["TokensGetData"];
                        };
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve token due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Published Token by Slug
         * @description Retrieve a single published cryptocurrency token using its slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The slug of the cryptocurrency token */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published token retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["TokensGetData"];
                        };
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Token not found or is not published */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve token due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token Quotes
         * @description Fetch real-time quotes and market data for specific tokens from CoinMarketCap.
         */
        get: {
            parameters: {
                query: {
                    /** @description List of token slugs to get quotes for.<br>Example: bitcoin,ethereum,sui */
                    slugs: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token quotes retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["TokensQuotesGetItem"][];
                        };
                    };
                };
                /** @description Invalid slug(s) provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve token quotes due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to fetch data from market data provider */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description Retrieve a list of messages with support for search, sender filtering, and pagination.
         */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    /** @description List of sender emails to filter by.<br>Example: example1@gmail.com,example2@gmail.com */
                    senders?: string[];
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of messages retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: components["schemas"]["PaginatedMessagesGetItem"];
                        };
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to retrieve messages due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Send Message
         * @description Create a new message from the contact form.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Whether to trigger an external notification (e.g. email) */
                    notify?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MessagesPostBody"];
                };
            };
            responses: {
                /** @description Message sent successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                /** Format: email */
                                email: string;
                                message: string;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Invalid form data provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to send message due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imgbb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image to ImgBB
         * @description Proxies an image upload to the ImgBB service and gets the resulting URLs.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description The image file to upload
                         */
                        image?: string;
                    };
                };
            };
            responses: {
                /** @description Image uploaded to ImgBB successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data: {
                                /** Format: uuid */
                                id: string;
                                imgbbId: string;
                                title: string;
                                url: string;
                                width: number;
                                height: number;
                                size: number;
                                fileName: string;
                                mimeType: string;
                                deleteUrl: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: uuid */
                                createdBy: string | null;
                            };
                        };
                    };
                };
                /** @description No image file provided in the request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Invalid or missing API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to process image upload due to an internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to proxy upload to ImgBB service */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seed/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Demo Data
         * @description Initialize the database with sample data (Users, Posts, Tokens, Messages) for development and testing.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Demo data seeded successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Demo seeding is strictly forbidden in production */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Failed to seed demo data */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Successful signup response with user info */
        AuthSignupPostResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        ApiResponse: {
            success: boolean;
            message: string;
            errors?: {
                [key: string]: string[];
            };
            data?: unknown;
        };
        /** @description Data for account registration */
        AuthSignupPostBody: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        AuthVerifyPostBody: {
            /** @description The verification token received via email */
            token: string;
        };
        /** @description Successful signin response with tokens and user info */
        AuthSigninPostResponse: {
            user: components["schemas"]["UserMetadata"];
            accessToken: string;
            refreshToken: string;
        };
        UserMetadata: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        /** @description Credentials for signing in */
        AuthSigninPostBody: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthSignoutPostBody: {
            /** @description The refresh token to revoke */
            refreshToken: string;
        };
        /** @description Successful token refresh */
        AuthRefreshPostResponse: {
            user: components["schemas"]["UserMetadata"];
            accessToken: string;
            refreshToken: string;
        };
        AuthRefreshPostBody: {
            /** @description The opaque refresh token */
            refreshToken: string;
        };
        /** @description Successful retrieval of current user info */
        AuthMeGetResponse: components["schemas"]["UserMetadata"] & {
            avatar?: components["schemas"]["AssetMetadata"];
            /**
             * @description The programmatic name of the assigned role
             * @enum {string}
             */
            role: "super_admin" | "admin" | "posts_manager" | "tokens_manager" | "member";
            /** @description List of programmatic permission keys */
            permissions: string[];
        };
        AssetMetadata: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            filename: string;
            size: number;
            mimeType?: string | null;
            width?: number | null;
            height?: number | null;
        } | null;
        UsersGetResponse: {
            items: components["schemas"]["UsersGetItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        UsersGetItem: components["schemas"]["UserMetadata"] & {
            avatar: components["schemas"]["AssetMetadata"];
            /** @enum {string} */
            role: "super_admin" | "admin" | "posts_manager" | "tokens_manager" | "member";
            /** @enum {string} */
            status: "active" | "inactive" | "suspended" | "banned";
            isEmailVerified: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
        };
        Pagination: {
            /** @description Total number of items matching the filters */
            total: number;
            /** @description Current page number */
            page: number;
            /** @description Number of items per page */
            limit: number;
            /** @description Total number of pages */
            totalPages: number;
        };
        UsersIdGetResponse: components["schemas"]["UserMetadata"] & {
            avatar: components["schemas"]["AssetMetadata"];
            /** @enum {string} */
            role: "super_admin" | "admin" | "posts_manager" | "tokens_manager" | "member";
            /** @enum {string} */
            status: "active" | "inactive" | "suspended" | "banned";
            isEmailVerified: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
        };
        UsersIdPatchBody: {
            name?: string;
            /** Format: uuid */
            avatarId?: string | null;
        };
        UsersIdStatusPutBody: {
            /** @enum {string} */
            status: "active" | "inactive" | "suspended" | "banned";
        };
        UsersIdRolePutBody: {
            /**
             * @description The role name (e.g. "admin", "member")
             * @enum {string}
             */
            role: "super_admin" | "admin" | "posts_manager" | "tokens_manager" | "member";
        };
        PaginatedPostsGetItem: {
            items: components["schemas"]["PostsGetItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        PostsGetItem: {
            /** Format: uuid */
            id: string;
            title: string;
            slug: string;
            excerpt: string;
            /** @enum {string} */
            section: "news" | "education" | "research" | "activity";
            /** @enum {string} */
            type: "article" | "webinar" | "video" | "headline";
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            isFeatured: boolean;
            /** Format: date-time */
            eventDate: string | null;
            externalLink: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            createdBy: components["schemas"]["UserMetadata"] & (Record<string, never> | null);
            updatedBy: components["schemas"]["UserMetadata"] & (Record<string, never> | null);
            coverImage: components["schemas"]["AssetMetadata"];
        };
        PostsGetData: {
            /** Format: uuid */
            id: string;
            title: string;
            slug: string;
            excerpt: string;
            content: string;
            /** @enum {string} */
            section: "news" | "education" | "research" | "activity";
            /** @enum {string} */
            type: "article" | "webinar" | "video" | "headline";
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            isFeatured: boolean;
            /** Format: date-time */
            eventDate: string | null;
            externalLink: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            createdBy: components["schemas"]["UserMetadata"] & (Record<string, never> | null);
            updatedBy: components["schemas"]["UserMetadata"] & (Record<string, never> | null);
            coverImage: components["schemas"]["AssetMetadata"];
        };
        PaginatedTokensGetItem: {
            items: components["schemas"]["TokensGetItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        TokensGetItem: {
            /** Format: uuid */
            id: string;
            slug: string;
            rank: number;
            name: string;
            ticker: string;
            /** @enum {string} */
            shariaStatus: "halal" | "haram" | "syubhat";
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            excerpt: string;
            tradingviewSymbol: string | null;
            website: string;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            createdBy: components["schemas"]["UserMetadata"] & (Record<string, never> | null);
            updatedBy: components["schemas"]["UserMetadata"] & (Record<string, never> | null);
            logo: components["schemas"]["AssetMetadata"];
        };
        TokensGetData: {
            /** Format: uuid */
            id: string;
            slug: string;
            rank: number;
            name: string;
            ticker: string;
            /** @enum {string} */
            shariaStatus: "halal" | "haram" | "syubhat";
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            excerpt: string;
            tradingviewSymbol: string | null;
            website: string;
            content: string;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            createdBy: components["schemas"]["UserMetadata"] & (Record<string, never> | null);
            updatedBy: components["schemas"]["UserMetadata"] & (Record<string, never> | null);
            logo: components["schemas"]["AssetMetadata"];
        };
        TokensQuotesGetItem: {
            slug: string;
            rank: number;
            infiniteSupply: boolean;
            maxSupply: number | null;
            circulatingSupply: number;
            priceUsd: number;
            marketCapUsd: number;
            marketCapDominance: number;
            percentChange24h: number;
        };
        PaginatedMessagesGetItem: {
            items: components["schemas"]["MessagesGetItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        MessagesGetItem: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        MessagesPostBody: {
            name: string;
            /** Format: email */
            email: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
