services:
  app:
    image: node:24-alpine
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      # Override DATABASE_URL from .env
      # This is to ensure the app can connect to the correct database
      # So we must replace the "localhost" with "db"
      - DATABASE_URL=postgres://root:mysecretpassword@db:5432/local
    ports:
      - 5172:5172
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5172"

  db:
    image: postgres:18-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=local
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
