CREATE TABLE "team_members" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" varchar(100),
	"name" varchar(150) NOT NULL,
	"credentials" varchar(150),
	"role" varchar(150) NOT NULL,
	"image_id" uuid,
	"image_url" text,
	"description" text NOT NULL,
	"focus" varchar(255) NOT NULL,
	"contribution" text,
	"joined" varchar(100),
	"expertise" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"order_index" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid,
	CONSTRAINT "team_members_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
INSERT INTO "team_members" ("slug", "name", "credentials", "role", "image_url", "description", "focus", "contribution", "joined", "expertise", "order_index", "is_active")
VALUES
('devin', 'Ust. Devin Halim Wijaya', 'B.B.A., M.Sc.', 'Board of Commissioners', '/team/board-devin-halim-wijaya.webp', 'Mendukung penguatan perspektif syariah CryptoSharia melalui kajian fikih muamalah, fatwa aset kripto, dan screening aset digital.', 'Fikih Muamalah & Screening Syariah', 'Pemateri MasterClass CryptoSharia 2026 pada sesi Fikih Muamalah & Fatwa Crypto serta Screening Koin & Bedah Kasus.', NULL, '[{"title":"Fikih Muamalah","description":"Prinsip transaksi dalam Islam"},{"title":"Fatwa Crypto","description":"Kajian hukum aset digital"},{"title":"Screening Syariah","description":"Penilaian aset dari aspek syariah"},{"title":"Aset Digital","description":"Kajian produk dan transaksi crypto"}]'::jsonb, 0, true),
('laksamana', 'Ust. Tengku Muhammad Laksamana Lelawangsa', 'S.Kom., Lc.', 'Board of Commissioners', '/team/board-muhammad-laksamana-lelawangsa.webp', 'Pendakwah dan edukator syariah yang membahas penerapan hukum Islam pada transaksi keuangan modern, termasuk forex, futures, dan aset kripto.', 'Fikih Muamalah & Hukum Transaksi Modern', 'Pemateri webinar CryptoSharia mengenai hukum Forex, Futures, dan Crypto dalam Islam.', NULL, '[{"title":"Fikih Muamalah","description":"Hukum transaksi dalam Islam"},{"title":"Forex & Futures","description":"Kajian dari perspektif syariah"},{"title":"Aset Kripto","description":"Hukum aset digital dalam Islam"},{"title":"Dakwah & Edukasi","description":"Penyampaian literasi hukum Islam"}]'::jsonb, 1, true),
('ali', 'Ust. Ali Hasan Bawazier', NULL, 'Board of Commissioners', '/team/board-ali-hasan-bawazier.webp', 'Berperan dalam pembinaan nilai dan edukasi syariah di lingkungan CryptoSharia serta komunitas CryptoSharia Forum.', 'Pembinaan & Edukasi Syariah', 'Terlibat dalam Crypto Syariah Series 2025 sebagai Pembina CryptoSharia Forum.', NULL, '[{"title":"Pembinaan Syariah","description":"Pembinaan nilai dan prinsip syariah"},{"title":"Edukasi Islam","description":"Literasi dan pembinaan komunitas"}]'::jsonb, 2, true),
('dea', 'Dea Saka Kurnia Putra', NULL, 'Board of Commissioners', '/team/board-dea-saka-kurnia-putra.webp', 'Founder Asosiasi Aset Kripto Syariah Indonesia (AKSI) yang aktif membahas blockchain, Web3, smart contract, dan penerapan teknologi terdesentralisasi.', 'Blockchain & Web3', 'Pembicara talkshow Blockchain Frontier pada NUSHAFEST 2025.', NULL, '[{"title":"Blockchain","description":"Teknologi dan implementasi blockchain"},{"title":"Web3","description":"Ekosistem internet terdesentralisasi"},{"title":"Smart Contract","description":"Aplikasi berbasis blockchain"},{"title":"Infrastruktur Digital","description":"Implementasi teknologi blockchain"}]'::jsonb, 3, true),
('sholahuddin', 'Sholahuddin Al Ayyubi', NULL, 'Chief Executive Officer', '/team/ceo-sholahuddin-al-ayyubi.webp', 'Memimpin arah perusahaan, pengembangan kemitraan, dan pengambilan keputusan strategis CryptoSharia.', 'Strategi Perusahaan & Partnership', 'Pemateri MasterClass CryptoSharia 2026 untuk topik Peta Industri Crypto & Web3.', NULL, '[{"title":"Strategi","description":"Arah dan prioritas perusahaan"},{"title":"Leadership","description":"Kepemimpinan organisasi"},{"title":"Partnership","description":"Pengembangan kemitraan strategis"},{"title":"Crypto & Web3","description":"Pemetaan industri aset digital"}]'::jsonb, 4, true),
('ghalib', 'Ghalib Ammar Ahsan', NULL, 'Chief Operating Officer', '/team/coo-ghalib-ammar-ahsan.webp', 'Mengawal operasional dan koordinasi program agar strategi CryptoSharia dapat dieksekusi secara terstruktur.', 'Operasional & Koordinasi Program', 'Ketua Pelaksana Nusantara Sharia Finance Festival (NUSHAFEST) 2025.', NULL, '[{"title":"Operasional","description":"Pelaksanaan aktivitas organisasi"},{"title":"Koordinasi Program","description":"Sinkronisasi pelaksanaan kegiatan"},{"title":"Pelaksanaan Event","description":"Koordinasi program dan kegiatan"}]'::jsonb, 5, true),
('haidar', 'Habibullah Haidar Al Atsary', NULL, 'Chief Financial Officer', '/team/cfo-habibullah-haidar-al-atsary.webp', 'Mengelola fungsi keuangan CryptoSharia, mulai dari arus kas dan anggaran hingga pelaporan dan evaluasi kinerja finansial.', 'Finance & Financial Control', NULL, NULL, '[{"title":"Cashflow","description":"Pengelolaan arus kas"},{"title":"Budgeting","description":"Perencanaan dan kontrol anggaran"},{"title":"Laporan Keuangan","description":"Penyusunan laporan finansial"},{"title":"Evaluasi Profit","description":"Evaluasi performa finansial"}]'::jsonb, 6, true),
('fikri', 'Muhammad Fikri Alfarizi', NULL, 'Chief Syariah Business Officer', '/team/csbo-muhammad-fikri-alfarizi.webp', 'Memimpin fungsi bisnis syariah CryptoSharia, meliputi analisis, screening aset, dan standardisasi kepatuhan syariah.', 'Analisis & Kepatuhan Syariah', 'Menjalankan fungsi analisis syariah di PT Kripto Syariah Indonesia.', '25 Mei 2025', '[{"title":"Analisis Syariah","description":"Analisis aktivitas dan produk"},{"title":"Screening Koin","description":"Penilaian kepatuhan aset"},{"title":"Fikih Muamalah","description":"Landasan transaksi syariah"},{"title":"Sharia Compliance","description":"Standardisasi kepatuhan syariah"}]'::jsonb, 7, true),
('bintang', 'Bintang Fajar Ramadhan', NULL, 'Chief Analytics Officer', '/team/cao-bintang-fajar-ramadhan.webp', 'Memimpin fungsi analytics dengan fokus pada riset pasar dan proyek, analisis teknikal dan fundamental, manajemen risiko, serta portofolio.', 'Market & Crypto Analytics', 'Terlibat sebagai pengisi materi analisis dalam roadmap edukasi CryptoSharia.', NULL, '[{"title":"Technical Analysis","description":"Analisis teknikal dan market structure"},{"title":"Fundamental","description":"Riset fundamental dan narasi"},{"title":"Risk Management","description":"Pengelolaan risiko investasi"},{"title":"Portfolio Management","description":"Pengelolaan portofolio"}]'::jsonb, 8, true),
('rifatul', 'Rif''atul Widaad Khotibin Tamhid', NULL, 'Chief Marketing Officer', '/team/cmo-rifatul-widaad-khotibin-tamhid.webp', 'Memimpin marketing dan media melalui pengembangan konten, branding, strategi kanal, dan pertumbuhan platform digital CryptoSharia.', 'Branding, Media & Marketing', NULL, NULL, '[{"title":"Creative Content","description":"Pengembangan konten digital"},{"title":"Branding","description":"Pengembangan identitas brand"},{"title":"Strategi Media","description":"Strategi distribusi dan kanal"},{"title":"Platform Digital","description":"Pengembangan kanal digital"}]'::jsonb, 9, true),
('axellyo', 'Mokhamad Axellyo Ghani Adam', NULL, 'Chief Communication Officer', '/team/cco-mokhamad-axellyo-ghani-adam.webp', 'Memimpin komunikasi dan engagement komunitas, termasuk pengelolaan interaksi anggota serta pelaksanaan aktivitas komunitas CryptoSharia.', 'Communication & Community Engagement', 'Terlibat sebagai PIC kegiatan komunitas dan pengelolaan engagement grup CryptoSharia.', NULL, '[{"title":"Komunikasi","description":"Komunikasi dengan komunitas"},{"title":"Community Engagement","description":"Aktivasi dan interaksi anggota"},{"title":"Aktivitas Komunitas","description":"Pelaksanaan kegiatan komunitas"}]'::jsonb, 10, true)
ON CONFLICT ("slug") DO NOTHING;
