export const ACCESS_TOKEN_EXPIRES_IN_SECONDS = 15 * 60;
export const REFRESH_TOKEN_EXPIRES_IN_DAYS = 15;
export const VERIFICATION_TOKEN_EXPIRES_IN_HOURS = 6;
export const PASSWORD_RESET_TOKEN_EXPIRES_IN_MINUTES = 30;
export const ACCESS_TOKEN_ISSUER = 'api.cryptosharia.id';
